version: "3.9"
services:
  process:
    image: camundamonitoring
    deploy:
      replicas: 3
    ports:
      - "8080:8080"
    networks:
      - camunda-overlay
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/process-engine
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: monitoring
      CAMUNDA_MONITORING_SNAPSHOT_ENABLED: "false"

  process-monitoring:
    image: camundamonitoring
    deploy:
      replicas: 1
    networks:
      - camunda-overlay
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/process-engine
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin


  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: process-engine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - camunda-overlay
  adminer:
    image: adminer
    ports:
      - 7080:8080
    networks:
      - camunda-overlay

  prometheus:
    image: prom/prometheus
    deploy:
      replicas: 1
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus

    networks:
      - camunda-overlay

networks:
  camunda-overlay:
    driver: overlay
    attachable: true

volumes:
  db-data:
    driver: local
